package com.ayuchat.domain;

public enum AuthErrorCode {
    INVALID_PHONE,
    INVALID_SCENE,
    INVALID_CODE,
    INVALID_PASSWORD,
    INVALID_VERIFY_TOKEN,
    INVALID_CREDENTIALS,
    PHONE_ALREADY_REGISTERED,
    PHONE_NOT_FOUND,
    SMS_RATE_LIMIT,
    VERIFY_RATE_LIMIT,
    ACCOUNT_DISABLED,
    UNAUTHORIZED
}
