package com.ayuchat.domain;

public enum ChatErrorCode {
    USER_NOT_FOUND,
    CANNOT_ADD_SELF,
    ALREADY_FRIENDS,
    FRIEND_REQUEST_PENDING,
    FRIEND_REQUEST_NOT_FOUND,
    FORBIDDEN,
    INVALID_MESSAGE,
    NOT_FRIENDS,
    CONVERSATION_NOT_FOUND,
    INVALID_MESSAGE_CONTENT,
    MESSAGE_TOO_LONG
}
